=== Harshit-Anandd/BridgeLabz-Training/java-io-streams-practice/gcr-codebase/JavaIOStreamsConcepts/src/main/resources/json/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "age": {
            "type": "integer",
            "minimum": 18
        },
        "email": {
            "type": "string",
            "format": "email"
        }
    },
    "required": [
        "id",
        "name",
        "email"
    ]
}

=== Harshit-Anandd/BridgeLabz-Training/java-io-streams-practice/gcr-codebase/JavaIOStreamsConcepts/src/main/resources/json/users.json
[
    {
        "id": 1,
        "name": "Alice",
        "age": 25,
        "email": "alice@example.com"
    },
    {
        "id": 2,
        "name": "Bob",
        "age": 30,
        "email": "bob@example.com"
    },
    {
        "id": 3,
        "name": "Charlie",
        "age": 22,
        "email": "charlie@example.com"
    }
]
